= muval
:package: com.github.rahulsom
:package-path: com/github/rahulsom
:package-path-encoded: com%2Fgithub%2Frahulsom
:snapshot-prefix: image:https://img.shields.io/maven-metadata/v?metadataUrl=https%3A%2F%2Fcentral.sonatype.com%2Frepository%2Fmaven-snapshots%2F{package-path-encoded}%2F
:snapshot-middle: %2Fmaven-metadata.xml&style=for-the-badge&label=S[alt=Maven Snapshot,height=30,link="https://central.sonatype.com/repository/maven-snapshots/{package-path}/
:snapshot-suffix: /maven-metadata.xml"]
:central-prefix: image:https://img.shields.io/maven-central/v/{package}/
:central-middle: ?style=for-the-badge&label=R&color=green[alt=Maven Central Version,height=30,link="https://central.sonatype.com/artifact/{package}/
:central-suffix: /overview"]
:deprecated-middle: ?style=for-the-badge&label=R&color=lightgrey[alt=Maven Central Version,height=30,link="https://central.sonatype.com/artifact/{package}/

Meaningful Use Validator based on NIST's own.

image:https://img.shields.io/github/commits-since/rahulsom/muval/latest?style=for-the-badge[GitHub commits since latest release, link="https://github.com/rahulsom/muval/releases/new"]

== Introduction

NIST's Meaningful Use Validator is great to check if your CCDs are valid.
However it runs as as a Command Line Utility that outputs XML.
If you want to make validation part of your unit tests, you need it to be callable from code.
This project aims to do just that.
NIST made its code available http://cda-validation.nist.gov/cda-validation/downloads.html[here].
Also they consider their code to be public domain.
That makes it possible for this project to exist.
I am thankful for that.

== Usage

This supports the legacy CLI usage as well as programmatic usage

=== CLI Usage

Download the jar from http://oss.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.github.rahulsom&a=muval&v=LATEST&c=all[here]

Then use it
[source,bash]
----
java -jar muval-all.jar -input sampleCCD.xml -output result.xml
----

=== Programmatic usage

Import the dependency using maven, gradle, sbt, leingen or ivy.
Example below is for gradle.
Look up instructions for your build tool from this badge.

==== Available versions

{central-prefix}muval{central-middle}muval{central-suffix}
{snapshot-prefix}muval{snapshot-middle}muval{snapshot-suffix}

[source,gradle]
----
dependencies {
    // ...
    compile 'com.github.rahulsom:muval:<VERSION>'
}
----

Then use it in your code. This example is a Spock Specification. You could use it in test or production code.
[source,groovy]
----
import spock.lang.Specification

import static gov.nist.mu.validation.Rulesets.*
import static gov.nist.mu.validation.Validator.validate

class MyCcdSpec extends Specification {

    private InputStream file(String resourceName) {
        this.class.getClassLoader().getResourceAsStream(resourceName)
    }

    def "sample ccd should validate"() {
        when: "I validate a CCD"
        def result = validate(Cdar2c32, file('SampleCCDDocument.xml'), Ccd, Cda4Cdt, C32_v_2_5_c83_2_0)

        then: "There are 50 errors and 98 issues"
        result.allIssues.size() == 98
        result.errors.size() == 50
        result.otherIssues.isEmpty()
    }

}
----

== Updating Schema and Schematron files

The `downloadResources` task will do the job. You need to delete the `nist` directory before that.

[source,bash]
----
./gradlew downloadResources
----

If you run into network problems, you may rerun that command.

== Contributing

Please feel free to raise Issues with test cases or send Pull Requests. This uses the github issue tracker.